sudo: false
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
addons:
  apt:
    packages:
    - libpq-dev
  postgresql: "9.3"
notifications:
  hipchat:
    rooms:
      secure: Q/Rlseyo/iB7NVGhI6b5je8LHLpcEpkQZdgfUZCvwhbqZtvrIDiZ2UR9RdLvf+60qLgESuY58JwtRDEMRbximj92PdpA7RR/9KvSmT5KSB5EVVwM7GFtLZChiSztk9VDt43KvizG+1kXbf/cfEu5OdLJ+PZsg5d/yNEXMsYhAXE=
